name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.14]  # Specify the Python version you are using

    env:
      PATH: .venv/bin:${{ env.PATH }}  # Prepend .venv/bin to PATH for all steps

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Verify Make Installation
        run: make --version  # Optional: Verify that 'make' is installed correctly

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create Virtual Environment
        run: make venv

      - name: Install Dependencies
        run: make install

      - name: Run Model Tests
        run: make model-test

      - name: Run API Tests
        run: make api-test
        
      - name: Build Python Package
        run: make build

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/*.whl
